# Generated by Django 6.0.6 on 2026-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150, verbose_name='Название ресторана')),
                ('services', models.TextField(verbose_name='Перечень предоставляемых услуг')),
                ('history_text', models.TextField(verbose_name='История ресторана')),
                ('mission_text', models.TextField(verbose_name='Миссия')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Главное изображение')),
                ('hall_plan', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Схема зала')),
            ],
            options={
                'verbose_name': 'Наполнение сайта',
                'verbose_name_plural': 'Наполнения сайта',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
