# Generated by Django 6.0.6 on 2026-06-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_feedback_alter_sitecontent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="about",
            field=models.TextField(default=None, verbose_name="Описание"),
            preserve_default=False,
        ),
    ]
