# Generated by Django 6.0.6 on 2026-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitecontent_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="email",
        ),
        migrations.AddField(
            model_name="feedback",
            name="phone_number",
            field=models.CharField(
                default=None, max_length=15, unique=True, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
    ]
