# Generated by Django 6.0.6 on 2026-06-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_feedback_email_feedback_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
    ]
