# Generated by Django 6.0.6 on 2026-06-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_feedback_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
