# Generated by Django 6.0.6 on 2026-06-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_teammember_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitecontent",
            options={
                "verbose_name": "Наполнение сайта",
                "verbose_name_plural": "Наполнение сайта",
            },
        ),
    ]
