# Generated by Django 6.0.6 on 2026-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_mady_by_staff",
            field=models.BooleanField(default=False, verbose_name="Создано менеджером"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
    ]
