# Generated by Django 6.0.6 on 2026-06-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_reservation_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["created_at"],
                "permissions": [("view_all_reservations", "Can view all reservations")],
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронирования",
            },
        ),
    ]
