# Generated by Django 6.0.6 on 2026-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("view_all_reservations", "Can view all reservations"),
                    ("make_phone_reservations", "Can create phone reservations"),
                ],
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронирования",
            },
        ),
    ]
